version: "3.9"

services:
  backend-litestar:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        progress: plain

    volumes:
      - './backend:/backend'

    ports:
      - "${LITESTAR_API_PORT}:${LITESTAR_API_PORT}"

    healthcheck:
      test: curl --fail http://localhost:${LITESTAR_API_PORT}/testing || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - linknet

    env_file: .env

#  backend-fastapi:
#    restart: always
#    build:
#      context: ./apifast
#      dockerfile: ./Dockerfile
#      args:
#        progress: plain
#
#    volumes:
#      - './apifast:/apifast'
#
#    ports:
#      - "${FAST_API_PORT}:${FAST_API_PORT}"
#
#    healthcheck:
#      test: curl --fail http://localhost:${FAST_API_PORT}/testing || exit 1
#      interval: 10s
#      timeout: 10s
#      start_period: 10s
#      retries: 3
#    networks:
#      - linknet
#
#    env_file: .env


  database:
    image: postgres
    restart: always

    volumes:
      - ./database/volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    networks:
      - linknet

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        progress: plain

    volumes:
      - './frontend/app:/frontend/app'

    ports:
      - "8501:8501"

    healthcheck:
      test: curl --fail http://localhost:8501/_stcore/health || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - linknet

    env_file: .env

networks:
  linknet:
    driver: bridge